#!/bin/sh

function force_format()
{
    for FILE in $(git diff-index --name-only --cached HEAD)
    do
        if [ -f ${FILE} ];then
            sed -i -E 's/[[:space:]]*$//g' ${FILE}
            dos2unix ${FILE}
            git add ${FILE}
        fi
    done
}

if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
   force_format
fi
